-- 1. Tạo bảng riêng cho Hướng dẫn khai thác thuộc Học liệu
create table if not exists public.huong_dan_hoc_lieu (
  id bigint generated by default as identity primary key,
  hoc_lieu_id bigint references public.hoc_lieu(id) on delete cascade,
  noi_dung text not null,
  thu_tu_hien_thi int default 1,
  created_at timestamptz default now()
);

-- 2. Tạo bảng riêng cho Câu hỏi luyện tập thuộc Học liệu
create table if not exists public.cau_hoi_hoc_lieu (
  id bigint generated by default as identity primary key,
  hoc_lieu_id bigint references public.hoc_lieu(id) on delete cascade,
  noi_dung_cau_hoi text not null,
  goi_y_dap_an text,
  thu_tu_hien_thi int default 1,
  created_at timestamptz default now()
);

-- 3. Cấu hình Row Level Security (RLS)
alter table public.huong_dan_hoc_lieu enable row level security;
alter table public.cau_hoi_hoc_lieu enable row level security;

-- Policies cho huong_dan_hoc_lieu
drop policy if exists "Cho phap doc public huong dan hoc lieu" on public.huong_dan_hoc_lieu;
create policy "Cho phap doc public huong dan hoc lieu"
  on public.huong_dan_hoc_lieu for select using (true);

drop policy if exists "Cho phap quan tri vien thay doi huong dan hoc lieu" on public.huong_dan_hoc_lieu;
create policy "Cho phap quan tri vien thay doi huong dan hoc lieu"
  on public.huong_dan_hoc_lieu for all using (auth.role() = 'authenticated');

-- Policies cho cau_hoi_hoc_lieu
drop policy if exists "Cho phap doc public cau hoi hoc lieu" on public.cau_hoi_hoc_lieu;
create policy "Cho phap doc public cau hoi hoc lieu"
  on public.cau_hoi_hoc_lieu for select using (true);

drop policy if exists "Cho phap quan tri vien thay doi cau hoi hoc lieu" on public.cau_hoi_hoc_lieu;
create policy "Cho phap quan tri vien thay doi cau hoi hoc lieu"
  on public.cau_hoi_hoc_lieu for all using (auth.role() = 'authenticated');
