-- 1. Bổ sung cột huong_dan_khai_thac vào bảng hoc_lieu nếu chưa tồn tại
alter table public.hoc_lieu add column if not exists huong_dan_khai_thac text;

-- 2. Tạo bảng riêng quản lý các câu hỏi luyện tập theo từng học liệu
create table if not exists public.cau_hoi_hoc_lieu (
  id bigint generated by default as identity primary key,
  hoc_lieu_id bigint references public.hoc_lieu(id) on delete cascade,
  noi_dung_cau_hoi text not null,
  goi_y_dap_an text,
  thu_tu_hien_thi int default 1,
  created_at timestamptz default now()
);

-- 3. Cấu hình Row Level Security (RLS) cho cau_hoi_hoc_lieu
alter table public.cau_hoi_hoc_lieu enable row level security;

drop policy if exists "Cho phap doc public cau hoi hoc lieu" on public.cau_hoi_hoc_lieu;
create policy "Cho phap doc public cau hoi hoc lieu"
  on public.cau_hoi_hoc_lieu for select using (true);

drop policy if exists "Cho phap quan tri vien thay doi cau hoi hoc lieu" on public.cau_hoi_hoc_lieu;
create policy "Cho phap quan tri vien thay doi cau hoi hoc lieu"
  on public.cau_hoi_hoc_lieu for all using (auth.role() = 'authenticated');
