const commonStatusFields = [
  { name: "da_xuat_ban", label: "Đã xuất bản", type: "boolean" },
];

const references = {
  chuDe: { table: "chu_de", labelField: "ten_chu_de", entityLabel: "chủ đề" },
  loaiHocLieu: {
    table: "loai_hoc_lieu",
    labelField: "ten_loai",
    entityLabel: "loại học liệu",
  },
  baiKiemTra: {
    table: "bai_kiem_tra",
    labelField: "tieu_de",
    entityLabel: "bài kiểm tra",
  },
  cauHoiKiemTra: {
    table: "cau_hoi_kiem_tra",
    labelField: "noi_dung_cau_hoi",
    entityLabel: "câu hỏi kiểm tra",
  },
  dapAnKiemTra: {
    table: "dap_an_kiem_tra",
    labelField: "noi_dung_dap_an",
    entityLabel: "đáp án kiểm tra",
  },
  ketQuaKiemTra: {
    table: "ket_qua_kiem_tra",
    labelField: "ho_ten_hoc_sinh",
    descriptionField: "ten_lop",
    entityLabel: "kết quả kiểm tra",
  },
  khaoSat: {
    table: "khao_sat",
    labelField: "tieu_de",
    entityLabel: "khảo sát",
  },
  cauHoiKhaoSat: {
    table: "cau_hoi_khao_sat",
    labelField: "noi_dung_cau_hoi",
    entityLabel: "câu hỏi khảo sát",
  },
  luaChonKhaoSat: {
    table: "lua_chon_khao_sat",
    labelField: "noi_dung_lua_chon",
    entityLabel: "lựa chọn khảo sát",
  },
  phanHoiKhaoSat: {
    table: "phan_hoi_khao_sat",
    labelField: "ho_ten_nguoi_tra_loi",
    descriptionField: "ten_lop",
    entityLabel: "phản hồi khảo sát",
  },
};

export const adminTables = [
  {
    name: "chu_de",
    label: "Chủ đề",
    fields: [
      { name: "ten_chu_de", label: "Tên chủ đề", required: true },
      { name: "duong_dan", label: "Đường dẫn", required: true },
      { name: "mo_ta", label: "Mô tả", type: "textarea" },
      { name: "thu_tu_hien_thi", label: "Thứ tự hiển thị", type: "number" },
      { name: "dang_hien_thi", label: "Đang hiển thị", type: "boolean" },
    ],
  },
  {
    name: "loai_hoc_lieu",
    label: "Loại học liệu",
    fields: [
      { name: "ten_loai", label: "Tên loại", required: true },
      { name: "duong_dan", label: "Đường dẫn", required: true },
      { name: "mo_ta", label: "Mô tả", type: "textarea" },
      { name: "thu_tu_hien_thi", label: "Thứ tự hiển thị", type: "number" },
      { name: "dang_hien_thi", label: "Đang hiển thị", type: "boolean" },
    ],
  },
  {
    name: "hoc_lieu",
    label: "Học liệu",
    fields: [
      { name: "tieu_de", label: "Tiêu đề", required: true },
      { name: "mo_ta", label: "Mô tả", type: "textarea" },
      { name: "chu_de_id", label: "Chủ đề", type: "number", reference: references.chuDe },
      {
        name: "loai_hoc_lieu_id",
        label: "Loại học liệu",
        type: "number",
        reference: references.loaiHocLieu,
      },
      {
        name: "duong_dan_file",
        label: "File hoặc link học liệu",
        required: true,
        upload: {
          provider: "cloudflare-r2",
          functionName: "r2-presign-upload",
          accept: ".pdf,.ppt,.pptx,.doc,.docx,.xls,.xlsx,.zip,.rar,.mp4,.mp3,.png,.jpg,.jpeg",
          helperText:
            "Chọn file để tải lên Cloudflare R2. Nếu là phiếu học tập hoặc tài liệu mở bằng link ngoài, dán URL trực tiếp ở ô bên dưới.",
        },
      },
      {
        name: "duong_dan_anh_dai_dien",
        label: "Ảnh đại diện / thư viện ảnh",
        upload: {
          provider: "cloudflare-r2",
          functionName: "r2-presign-upload",
          accept: ".png,.jpg,.jpeg,.webp",
          multiple: true,
          helperText:
            "Có thể chọn nhiều ảnh để tải lên. Mỗi ảnh sẽ được lưu thành một dòng, phù hợp cho infographic, sơ đồ tư duy, phiếu học tập preview.",
        },
      },
      { name: "ten_nguon", label: "Tên nguồn" },
      { name: "lop", label: "Lớp", type: "number" },
      { name: "noi_bat", label: "Nổi bật", type: "boolean" },
      ...commonStatusFields,
    ],
  },
  {
    name: "bai_kiem_tra",
    label: "Bài kiểm tra",
    fields: [
      { name: "tieu_de", label: "Tiêu đề", required: true },
      { name: "mo_ta", label: "Mô tả", type: "textarea" },
      { name: "chu_de_id", label: "Chủ đề", type: "number", reference: references.chuDe },
      { name: "thoi_gian_lam_bai_phut", label: "Thời gian làm bài", type: "number" },
      ...commonStatusFields,
    ],
  },
  {
    name: "cau_hoi_kiem_tra",
    label: "Câu hỏi kiểm tra",
    fields: [
      {
        name: "bai_kiem_tra_id",
        label: "Bài kiểm tra",
        type: "number",
        required: true,
        reference: references.baiKiemTra,
      },
      { name: "noi_dung_cau_hoi", label: "Nội dung câu hỏi", type: "textarea", required: true },
      { name: "duong_dan_anh_cau_hoi", label: "Đường dẫn ảnh câu hỏi" },
      { name: "giai_thich_dap_an", label: "Giải thích đáp án", type: "textarea" },
      { name: "diem", label: "Điểm", type: "number" },
      { name: "thu_tu_hien_thi", label: "Thứ tự hiển thị", type: "number" },
    ],
  },
  {
    name: "dap_an_kiem_tra",
    label: "Đáp án kiểm tra",
    fields: [
      {
        name: "cau_hoi_id",
        label: "Câu hỏi kiểm tra",
        type: "number",
        required: true,
        reference: references.cauHoiKiemTra,
      },
      { name: "noi_dung_dap_an", label: "Nội dung đáp án", required: true },
      { name: "la_dap_an_dung", label: "Là đáp án đúng", type: "boolean" },
      { name: "thu_tu_hien_thi", label: "Thứ tự hiển thị", type: "number" },
    ],
  },
  {
    name: "ket_qua_kiem_tra",
    label: "Kết quả kiểm tra",
    fields: [
      {
        name: "bai_kiem_tra_id",
        label: "Bài kiểm tra",
        type: "number",
        reference: references.baiKiemTra,
      },
      { name: "ho_ten_hoc_sinh", label: "Họ tên học sinh" },
      { name: "ten_lop", label: "Tên lớp" },
      { name: "ten_truong", label: "Tên trường" },
      { name: "tong_so_cau", label: "Tổng số câu", type: "number" },
      { name: "so_cau_dung", label: "Số câu đúng", type: "number" },
      { name: "diem_so", label: "Điểm số", type: "number" },
    ],
  },
  {
    name: "chi_tiet_ket_qua_kiem_tra",
    label: "Chi tiết kết quả kiểm tra",
    fields: [
      {
        name: "ket_qua_id",
        label: "Kết quả kiểm tra",
        type: "number",
        required: true,
        reference: references.ketQuaKiemTra,
      },
      {
        name: "cau_hoi_id",
        label: "Câu hỏi kiểm tra",
        type: "number",
        reference: references.cauHoiKiemTra,
      },
      {
        name: "dap_an_da_chon_id",
        label: "Đáp án đã chọn",
        type: "number",
        reference: references.dapAnKiemTra,
      },
      { name: "la_dap_an_dung", label: "Là đáp án đúng", type: "boolean" },
    ],
  },
  {
    name: "ban_do",
    label: "Bản đồ",
    fields: [
      { name: "tieu_de", label: "Tiêu đề", required: true },
      { name: "mo_ta", label: "Mô tả", type: "textarea" },
      { name: "chu_de_id", label: "Chủ đề", type: "number", reference: references.chuDe },
      { name: "duong_dan_anh_ban_do", label: "Đường dẫn ảnh bản đồ" },
      { name: "duong_dan_file_ban_do", label: "Đường dẫn file bản đồ" },
      { name: "duong_dan_nhung", label: "Đường dẫn nhúng" },
      ...commonStatusFields,
    ],
  },
  {
    name: "vung_kinh_te",
    label: "Vùng kinh tế",
    fields: [
      { name: "ten_vung", label: "Tên vùng", required: true },
      { name: "duong_dan", label: "Đường dẫn", required: true },
      { name: "mo_ta", label: "Mô tả", type: "textarea" },
      { name: "the_manh", label: "Thế mạnh", type: "textarea" },
      { name: "nganh_cong_nghiep_chinh", label: "Ngành công nghiệp chính", type: "textarea" },
      { name: "nganh_nong_nghiep_chinh", label: "Ngành nông nghiệp chính", type: "textarea" },
      { name: "thanh_pho_tieu_bieu", label: "Thành phố tiêu biểu" },
      { name: "duong_dan_anh", label: "Đường dẫn ảnh" },
      { name: "thu_tu_hien_thi", label: "Thứ tự hiển thị", type: "number" },
      ...commonStatusFields,
    ],
  },
  {
    name: "tin_tuc_tu_lieu",
    label: "Tin tức tư liệu",
    fields: [
      { name: "tieu_de", label: "Tiêu đề", required: true },
      { name: "duong_dan", label: "Đường dẫn", required: true },
      { name: "tom_tat", label: "Tóm tắt", type: "textarea" },
      { name: "noi_dung", label: "Nội dung", type: "textarea" },
      { name: "chu_de_id", label: "Chủ đề", type: "number", reference: references.chuDe },
      { name: "duong_dan_anh_dai_dien", label: "Đường dẫn ảnh đại diện" },
      { name: "ten_nguon", label: "Tên nguồn" },
      { name: "duong_dan_nguon", label: "Đường dẫn nguồn" },
      { name: "ngay_xuat_ban", label: "Ngày xuất bản", type: "datetime-local" },
      ...commonStatusFields,
    ],
  },
  {
    name: "du_lieu_thong_ke",
    label: "Dữ liệu thống kê",
    fields: [
      { name: "tieu_de", label: "Tiêu đề", required: true },
      { name: "chu_de_id", label: "Chủ đề", type: "number", reference: references.chuDe },
      { name: "ten_chi_so", label: "Tên chỉ số", required: true },
      { name: "ten_dia_phuong", label: "Tên địa phương" },
      { name: "nam", label: "Năm", type: "number" },
      { name: "gia_tri", label: "Giá trị", type: "number" },
      { name: "don_vi", label: "Đơn vị" },
      { name: "ten_nguon", label: "Tên nguồn" },
      { name: "duong_dan_nguon", label: "Đường dẫn nguồn" },
      { name: "ghi_chu", label: "Ghi chú", type: "textarea" },
    ],
  },
  {
    name: "khao_sat",
    label: "Khảo sát",
    fields: [
      { name: "tieu_de", label: "Tiêu đề", required: true },
      { name: "mo_ta", label: "Mô tả", type: "textarea" },
      { name: "doi_tuong_khao_sat", label: "Đối tượng khảo sát" },
      { name: "dang_mo", label: "Đang mở", type: "boolean" },
    ],
  },
  {
    name: "cau_hoi_khao_sat",
    label: "Câu hỏi khảo sát",
    fields: [
      {
        name: "khao_sat_id",
        label: "Khảo sát",
        type: "number",
        required: true,
        reference: references.khaoSat,
      },
      { name: "noi_dung_cau_hoi", label: "Nội dung câu hỏi", type: "textarea", required: true },
      { name: "kieu_cau_hoi", label: "Kiểu câu hỏi", required: true },
      { name: "thu_tu_hien_thi", label: "Thứ tự hiển thị", type: "number" },
    ],
  },
  {
    name: "lua_chon_khao_sat",
    label: "Lựa chọn khảo sát",
    fields: [
      {
        name: "cau_hoi_id",
        label: "Câu hỏi khảo sát",
        type: "number",
        required: true,
        reference: references.cauHoiKhaoSat,
      },
      { name: "noi_dung_lua_chon", label: "Nội dung lựa chọn", required: true },
      { name: "thu_tu_hien_thi", label: "Thứ tự hiển thị", type: "number" },
    ],
  },
  {
    name: "phan_hoi_khao_sat",
    label: "Phản hồi khảo sát",
    fields: [
      {
        name: "khao_sat_id",
        label: "Khảo sát",
        type: "number",
        reference: references.khaoSat,
      },
      { name: "ho_ten_nguoi_tra_loi", label: "Họ tên người trả lời" },
      { name: "ten_lop", label: "Tên lớp" },
      { name: "ten_truong", label: "Tên trường" },
      { name: "doi_tuong_tra_loi", label: "Đối tượng trả lời" },
    ],
  },
  {
    name: "cau_tra_loi_khao_sat",
    label: "Câu trả lời khảo sát",
    fields: [
      {
        name: "phan_hoi_id",
        label: "Phản hồi khảo sát",
        type: "number",
        required: true,
        reference: references.phanHoiKhaoSat,
      },
      {
        name: "cau_hoi_id",
        label: "Câu hỏi khảo sát",
        type: "number",
        reference: references.cauHoiKhaoSat,
      },
      { name: "noi_dung_tra_loi", label: "Nội dung trả lời", type: "textarea" },
      {
        name: "lua_chon_da_chon_id",
        label: "Lựa chọn đã chọn",
        type: "number",
        reference: references.luaChonKhaoSat,
      },
    ],
  },
  {
    name: "gop_y_lien_he",
    label: "Góp ý liên hệ",
    fields: [
      { name: "ho_ten", label: "Họ tên" },
      { name: "email", label: "Email" },
      { name: "so_dien_thoai", label: "Số điện thoại" },
      { name: "ten_truong", label: "Tên trường" },
      { name: "tieu_de", label: "Tiêu đề" },
      { name: "noi_dung", label: "Nội dung", type: "textarea", required: true },
      { name: "trang_thai", label: "Trạng thái" },
    ],
  },
  {
    name: "cau_hinh_website",
    label: "Cấu hình website",
    fields: [
      { name: "khoa_cau_hinh", label: "Khóa cấu hình", required: true },
      { name: "gia_tri_cau_hinh", label: "Giá trị cấu hình", type: "textarea" },
    ],
  },
];
